version: "3.8"
services:
  botnoi-fazwaz-backend:
    build: .
    container_name: botnoi-fazwaz-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./tokens.db
      - PYTHONPATH=/app/src
    working_dir: /app/src
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
